---
  - name: Add Host to dvswitch
    local_action:
      module: vmware_dvs_host
      state: present
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username}}"
      password: "{{ vsphere_password }}"
      esxi_hostname: "{{ item.1 }}"
      switch_name: "{{ item.0.dvswitch_name }}"
      vmnics:
          - vmnic2
          - vmnic3
      validate_certs: False
    with_nested:
      - "{{ dvswitch_conf }}"
      - "{{ esxi_hostname }}"