---
  - name: Dvswitch portgroup
    local_action:
      module: vmware_dvs_portgroup
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username}}"
      password: "{{ vsphere_password }}"
      portgroup_name: "{{ item.1.dvswitch_portgroup_name }}"
      switch_name: "{{ item.0.dvswitch_name }}"
      vlan_id: "{{ item.1.dvswitch_vlan_id }}"
      num_ports: "{{ item.1.dvswitch_num_ports }}" 
      portgroup_type: earlyBinding # This is default in the vCenter it's called: Static Binding
      state: present
      validate_certs: False
    with_subelements:
      - "{{  dvswitch_conf }}"
      - dvswitch_portgroups