---
- hosts: 127.0.0.1
  connection: local
  any_errors_fatal: True

  roles:
    - vmware_create_dc
    - vmware_create_cluster
    - vmware_add_esxi
    - vmware_add_vswitch
    - vmware_add_portgroup
    - vmware_create_dvswitch
    - vmware_create_dvswitch_portgroup
    - vmware_add_esxi_dvswitch
    - vmware_ntp_configuration
    - vmware_advanced_settings
    - vmware_add_permissions
    - vmware_power_management

# In this Block we are adding the second NIC to the vswitch since it's not possible to do with current "vmware_vswitch" module
- hosts:
    - 192.168.1.55
    - 192.168.1.56
  vars:
    - esx_vswitch:
        - vswitch_number: vSwitch0
          vswitch_mtu: 1500
          vswitch_vmnics: vmnic1

  roles:
    - vmware_add_vswitch_workaround
    # This role restarts server
    - vmware_set_psp