---
- hosts: 127.0.0.1
  connection: local
  any_errors_fatal: True

  vars:
    - vsphere_hostname: lab01vcc01.oc.lab
      vsphere_username: ad_michal@oc.lab
      vsphere_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36316664373066313937353664366365383030633861633463663361356234646538353731333937
          3938636236353534306563353064623966646663643161620a353439633836313231323234663032
          63623235306537303730663035373535353638393537393163653161383233343466656337396665
          3361336638646336370a663533323932366162643230363164336432383733343536303734326161
          3034
      vsphere_dc_name: Ansible_DC
      vshpere_cluster_name: Ansible_Cluster
      esxi_hostname: 192.168.1.55
      esxi_username: root
      esxi_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65323239646535356565336463363937346238373231643535623734636664343362653739353066
          3066383431323137343535323561333537636631366166390a303365353437303064626366616165
          63353035356239656661613236663963643735643430666664653732333931663731323431663737
          3135646638353334310a643639306665646466623034656336626565613862313764393533303037
          6166
      dvswitch_name: lab01vcc01
      dvswitch_portgroup:
        - CSC_Heartbeat
        - CSC_Management

      vswitch_number: vSwitch0
      #vmnic_name:

      # List of ntp servers, HAS TO BE in HORIZONTAL format:
      esxi_ntp_servers: 0.vmware.pool.ntp.org, 1.vmware.pool.ntp.org, 2.vmware.pool.ntp.org

      # List for govc loop:
      esxi_hosts:
        - 192.168.1.56
        - 192.168.1.55
      # List for GOVC Nested loop
      esxi_advanced_settings:
        - option: Disk.QFullSampleSize
          value: 32
        - option: Disk.QFullThreshold
          value: 4
        - option: Disk.MaxLUN
          value: 255

  tasks:
    - name: "Create DC: {{ vsphere_dc_name }}"
      local_action:
        module: vmware_datacenter
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        datacenter_name: "{{ vsphere_dc_name }}"
        validate_certs: False
        state: present

    - name: "Create Cluster: {{ vshpere_cluster_name }}"
      local_action:
        module: vmware_cluster
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        datacenter_name: "{{ vsphere_dc_name }}"
        cluster_name: "{{ vshpere_cluster_name }}"
        validate_certs: False
        enable_ha: True
        enable_drs: True

    - name: Add ESXi to vSphere
      local_action:
        module: vmware_host
        state: present
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        datacenter_name: "{{ vsphere_dc_name }}"
        cluster_name: "{{ vshpere_cluster_name }}"
        esxi_hostname: "{{item}}"
        esxi_username: "{{ esxi_username }}"
        esxi_password: "{{ esxi_password }}"
        validate_certs: False
      with_items:
        - "{{ esxi_hosts }}"

    - name: "Create vswitch: {{ vswitch_number}}"
      local_action:
        module: vmware_vswitch
        state: present
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        switch_name: "{{ vswitch_number}}"
        nic_name: vmnic2
        mtu: 1500
        validate_certs: False

    - name: Create vswitch
      local_action:
        module: vmware_vswitch
        state: present
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        switch_name: "{{ vswitch_number}}"
        nic_name: vmnic3
        mtu: 1500
        validate_certs: False

    - name: Create Vmware Port Groups
      local_action:
        module: vmware_portgroup
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        switch_name: "{{ vswitch_number}}"
        portgroup_name: Management Network  # Name of the Interface
        vlan_id: 0
        validate_certs: False
        network_policy:
          promiscuous_mode: False
          forged_transmits: False
          mac_changes: False

    - name: "Create dvswitch"
      local_action:
        module: vmware_dvswitch
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        datacenter_name: "{{ item.1 }}"
        switch_name: "{{ item.0 }}"
        mtu: 1500                 # Default: 1500
        uplink_quantity: 2
        discovery_proto: cdp     # Default: cdp
        discovery_operation: listen # Default: listen
        state: present
        validate_certs: False
      with_nested:
        - "{{ dvswitch_name }}"
        - "{{ vsphere_dc_name }}"

    - name: Dvswitch portgroup
      local_action:
        module: vmware_dvs_portgroup
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        portgroup_name: "{{ item }}"
        switch_name: "{{ dvswitch_name }}"
        vlan_id: 0
        num_ports: 14
        portgroup_type: earlyBinding
        state: present
        validate_certs: False
      with_items:
        - "{{ dvswitch_portgroup }}"

    - name: Add Host to dvswitch
      local_action:
        module: vmware_dvs_host
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username}}"
        password: "{{ vsphere_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        switch_name: "{{ dvswitch_name }}"
        vmnics:
            - vmnic0
            - vmnic1
        state: present
        validate_certs: False

  # Interact with Shell localy for GOVC
    - name: Edit NTP configuration for ESXi host
      command: govc host.date.change -dc "{{ vsphere_dc_name }}" -host "{{ item }}" -server "{{ esxi_ntp_servers }}"
      # List for govc loop:
      with_items:
        - "{{ esxi_hosts }}"
  # Iterates over nested loop for each Host apply Option: Value:
    - name: Edit Advanced Settings
      command: govc host.option.set -dc "{{ vsphere_dc_name }}" -host "{{ item.0 }}" "{{ item.1.option }}" "{{ item.1.value }}"
      with_nested:
        - "{{ esxi_hosts }}"
        - "{{ esxi_advanced_settings }}"

  # Configure Permissions settings
  # https://<vCenter_server>/mob/?moid=AuthorizationManager&doPath=roleList
    - name:  Add Permissions
      command: govc permissions.set -u "{{ vsphere_hostname }}" -principal "oc\ansible" -role Admin -propagate=True

  # Configure Power Management
  # This although this apperas be working fine, vCenter doesn't reflect the new setting unles restarted
  # Ticket opened with vmware 17439099204
    - name:  Set Power Management
      command: govc host.option.set -dc "{{ vsphere_dc_name }}" -host "{{ item }}" Power.CpuPolicy "High Performance"
      with_items:
        - "{{ esxi_hosts }}"
