---
  - name: "Create Cluster"
    local_action:
      module: vmware_cluster
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username}}"
      password: "{{ vsphere_password }}"
      datacenter_name: "{{ item.0 }}"
      cluster_name: "{{ item.1 }}"
      enable_ha: "{{ item.2.ha }}"    # Default True
      enable_drs: "{{ item.3.drs }}"  # Default True
      validate_certs: False
    with_nested:
      - "{{ vsphere_dc_name }}"
      - "{{ vshpere_cluster_name }}"
      - "{{ cluster_ha_setting }}"
      - "{{ cluster_drs_setting }}"