---
# Get PSP Setting and export it as viariable psp_value
# This taks will always show as chnaged
  - name: Get PSP Configuration value
    shell: esxcli storage nmp satp list | grep -e '^VMW_SATP_ALUA\b' | awk '{print $2}'
    register: psp_value

  - name: Change VMW_SATP_ALUA to VMW_PSP_RR
    shell: esxcli storage nmp satp set --default-psp=VMW_PSP_RR --satp=VMW_SATP_ALUA | tee .psp.conf.setting
    when: psp_value.stdout != "VMW_PSP_RR"
    register: change_psp
    changed_when: >
      change_psp.stdout == "Default PSP for VMW_SATP_ALUA is now VMW_PSP_RR"
    failed_when: >
      change_psp.stdout != "Default PSP for VMW_SATP_ALUA is now VMW_PSP_RR"
    args:
      creates: .psp.conf.setting
      chdir: /


#!! This will reboot the esxi host, if the PSP value has been changed
  - name: Esxi host R_E_S_T_A_R_T
    command: reboot
    when: psp_value.stdout != "VMW_PSP_RR" and (change_psp|succeeded)