##################
# used varibles:
#
# esxi_hostname
# esxi_username
# esxi_password
# vsphere_hostname
# vsphere_username
# vsphere_password
# vsphere_dc_name
# vshpere_cluster_name
# vswitch_number
# vmnic_name
# vportgroup_name
#
####################
---
- hosts: 127.0.0.1
  connection: local
  any_errors_fatal: True
  roles:
    - vmware_create_dc
    - vmware_create_cluster
    - vmware_add_esxi
    - vmware_add_vswitch
    - vmware_add_portgroup