---
  # Create DC accepts more then one DC names so we can create multiple DC's in one go
  - name: Create DC
    local_action:
      module: vmware_datacenter
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username}}"
      password: "{{ vsphere_password }}"
      datacenter_name: "{{ item }}"
      validate_certs: False
      state: present
    with_items:
      - "{{ vsphere_dc_name }}"
