---
  - name: Create Cluster
    local_action:
      module: vmware_cluster
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username}}"
      password: "{{ vsphere_password }}"
      datacenter_name: "{{ vsphere_dc_name }}"
      cluster_name: "{{ vshpere_cluster_name }}"
      enable_ha: True
      enable_drs: True
