---
  - name: Create vSwitch
    local_action:
      module: vmware_vswitch
      state: present
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      switch_name: "{{ item.0.vswitch_number}}"
      nic_name: "{{ item.0.nics }}"
      mtu: "{{ item.1 }}"   #Default:1500
      validate_certs: False
    with_nested:
      - "{{esx_vswitch_ports}}"
      - "{{ vswitch_mtu }}"
