---
  - name: Create vSwitch
    local_action:
      module: vmware_vswitch
      state: present
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      switch_name: "{{ item.vswitch_number}}"
      nic_name: "{{ item.vswitch_vmnics }}"
      mtu: "{{ item.vswitch_mtu }}"   #Default:1500
      validate_certs: False
    with_items:
      - "{{esx_vswitch}}"