---
  - name: Create vSwitch
    local_action:
      module: vmware_vswitch
      state: present
      hostname: "{{ item.1 }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      switch_name: "{{ item.0.vswitch_number}}"
      nic_name: "{{ item.0.vswitch_vmnics }}"
      mtu: "{{ item.0.vswitch_mtu }}"   #Default:1500
      validate_certs: False
    with_nested:
      - "{{esx_vswitch}}"
      - "{{ esxi_hostname }}"