---

  - name: Remove default NTP server
    replace:
      path: /etc/ntp.conf
      regexp: 'server\b 0\.pool\.ntp\.org'
      backup: yes

  - name: Add NTP servers
    lineinfile:
      path: /etc/ntp.conf
      insertafter: 'restrict\b 127\.0\.0\.1'
      state: present
      backup: yes
      line: "server {{ item }}"
    with_items:
      - "{{ esxi_ntp_servers }}"
    notify:
      - Restart Vmware hostd
      - Restart Vmware vpxa